# general settings
name: CDCN_x3_setting1
model_type: BlindSRModel
scale: 3
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 10
nonblindsr: false
degradation:
  random_kernel: True
  ksize: 21
  code_length: 10
  sig_min: 0.2
  sig_max: 3.0
  rate_iso: 1.0
  random_disturb: false
# dataset and data loader settings
datasets:
  train:
    name: DF2K
    type: BlindImageDataset
    dataroot_gt: /opt/data/private/wyx/DIV2K+Flickr2K/
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 192
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val:
    name: Set5G8
    type: PairedImageDataset
    dataroot_gt: /opt/data/private/wyx/Set5G8/HR/x3/
    dataroot_lq: /opt/data/private/wyx/Set5G8/LRblur/x3/
    io_backend:
      type: disk

# network structures
network_g:
  type: CDCN
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 64
  num_group: 5
  num_block: 10
  upscale: 3

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [100000, 200000, 300000, 400000]
    gamma: 0.5

  total_iter: 600000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
    
  detail_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

  structure_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 2e3
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 3
      test_y_channel: true

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 2e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
